name: Convert End-of-Line

on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Convert end-of-line characters
      uses: mikepenz/end-of-line-converter@v1
      with:
        files: |
          install_checkuser.sh
